default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  host: localhost

development:
  <<: *default
  database: bitshares_faucet_dev

test:
  <<: *default
  database: bitshares_faucet_test

production:
  <<: *default
  database: bitshares_faucet
